##
## EPITECH PROJECT, 2023
## B-PDG-300-LYN-3-1-PDGD02-erwann.laplante
## File description:
## Makefile
##

.PHONY : all clean fclean re

NAME = doop

SRC = DoOp.hs

CC = ghc

all: $(NAME)

$(NAME):
	echo "fake compilation"

clean:
	rm -rf DoOp.o DoOp.hi

fclean: clean
	rm -rf $(NAME)

re: fclean all
