apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default  
spec:
  type: ClusterIP
  selector:
    app: redis
    stage: backstage
  ports:
    - protocol: TCP
      port: 6379 
      targetPort: 6379